// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTw1PhM94-AnFx3aCQsYSkYz2bxCgYId0',
    appId: '1:390710313642:web:1ce7a48c786939374146d3',
    messagingSenderId: '390710313642',
    projectId: 'task-management-apps-863b9',
    authDomain: 'task-management-apps-863b9.firebaseapp.com',
    storageBucket: 'task-management-apps-863b9.appspot.com',
    measurementId: 'G-XBLCTP3D9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRlPkf9QO0z3N_U8EXleP1khAG1XMgeds',
    appId: '1:390710313642:android:6e0b10292fa7c22f4146d3',
    messagingSenderId: '390710313642',
    projectId: 'task-management-apps-863b9',
    storageBucket: 'task-management-apps-863b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACPQ0BDSSJfUA_8ivXRdQQne0LNyIPz00',
    appId: '1:390710313642:ios:3b7fde0a6dd8750f4146d3',
    messagingSenderId: '390710313642',
    projectId: 'task-management-apps-863b9',
    storageBucket: 'task-management-apps-863b9.appspot.com',
    androidClientId: '390710313642-aj9ajm7cjt24ed69jv5mrgm882vpo067.apps.googleusercontent.com',
    iosClientId: '390710313642-eppip3cd2k507tocucd87s8b1g5pcqe0.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACPQ0BDSSJfUA_8ivXRdQQne0LNyIPz00',
    appId: '1:390710313642:ios:3b7fde0a6dd8750f4146d3',
    messagingSenderId: '390710313642',
    projectId: 'task-management-apps-863b9',
    storageBucket: 'task-management-apps-863b9.appspot.com',
    androidClientId: '390710313642-aj9ajm7cjt24ed69jv5mrgm882vpo067.apps.googleusercontent.com',
    iosClientId: '390710313642-eppip3cd2k507tocucd87s8b1g5pcqe0.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );
}
